package com.example.artsymobileapp.components.network.types.artistDetailsType

data class Artwork(
    val _embedded: EmbeddedX,
    val _links: Links,
    val additional_information: String,
    val blurb: String,
    val can_acquire: Boolean,
    val can_inquire: Boolean,
    val can_share: Boolean,
    val category: String,
    val collecting_institution: String,
    val created_at: String,
    val cultural_maker: Any,
    val date: String,
    val dimensions: Dimensions,
    val exhibition_history: String,
    val iconicity: Double,
    val id: String,
    val image_rights: String,
    val image_versions: List<String>,
    val literature: String,
    val medium: String,
    val provenance: String,
    val published: Boolean,
    val sale_message: Any,
    val series: String,
    val signature: String,
    val slug: String,
    val sold: Boolean,
    val title: String,
    val unique: Boolean,
    val updated_at: String,
    val visibility_level: String,
    val website: String
)